name: Bloop, Bloop, Shop!
author: Pascal Laliberté
url: https://bloopbloop.shop
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
excerpt_separator: "<!-- MORE -->"
baseurl:
gems:
  - jekyll-sitemap
destination: public
exclude: [public, Gemfile, Gemfile.lock, Rakefile, README.md]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      lang: en
include: [".well-known"]

